name: Testing & Linting On Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build test environment
        run: docker compose build test

      - name: Run tests for all services
        run: |
          SERVICES=$(ls -d backend/services/* backend/libs/* | grep -oE '[^/]+$')
          for SERVICE in $SERVICES; do
            echo "Running tests for service: $SERVICE"
            docker compose run --rm test $SERVICE --all
          done
