name: Testing & Linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run Linter
        run: |
          set -e

          chmod +x ci/testing_for_all_services.sh

          ./ci/testing_for_all_services.sh isort || { echo "isort failed"; exit 1; }

          ./ci/testing_for_all_services.sh black || { echo "black failed"; exit 1; }

          ./ci/testing_for_all_services.sh bandit || { echo "bandit failed"; exit 1; }

          ./ci/testing_for_all_services.sh flake8 || { echo "flake8 failed"; exit 1; }

          ./ci/testing_for_all_services.sh mypy || { echo "mypy failed"; exit 1; }

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run Tests
        run: |
          set -e
          
          chmod +x ci/testing_for_all_services.sh

          ./ci/testing_for_all_services.sh pytest || { echo "pytest failed"; exit 1; }
