name: Testing & Linting On Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run tests for all services
        run: |
          chmod +x backend/test.sh # Make the script executable
          SERVICES=$(ls -d backend/services/* backend/libs/* | grep -oE '[^/]+$') #get all service names
          for SERVICE in $SERVICES; do
            echo "Running tests for service: $SERVICE"
            backend/test.sh $SERVICE --ci --all # Run for each service
          done
